Update architecture overview
ong-bitcoin-argentina/DIDI-SSI-Docs pull request #46
Opened 2021-07-08 18:56 UTC by MatiasOS

2021-07-08 21:16 UTC, tamarabag requested changes
:) (aunque no me gusta la palabra "aplicativo" que sugiero ja)

2021-07-08 21:16 UTC, tamarabag commented on docs/developers/solucion/arquitectura-overview.md
> +El issuer permite la creación de templates, pre credenciales y emisión de credenciales. Una vez emitidas las credenciales se almacenan en Mouro y son accedidas los los usuarios desde ai·di.
El issuer es el aplicativo para emisores DIDI que permite la creación de templates, pre credenciales y emisión de credenciales. Una vez emitidas las credenciales se almacenan en Mouro y son accedidas por los usuarios desde ai·di.

2021-07-08 21:16 UTC, tamarabag commented on docs/developers/solucion/arquitectura-overview.md
> +* Comunicación con Semillas
Comunicación con el emisor Semillas (middleware desarrollado para la automatización de la emisión de credenciales para este caso de implementación).

2021-07-12 20:28 UTC, MatiasOS commented on docs/developers/solucion/arquitectura-overview.md
> +El issuer permite la creación de templates, pre credenciales y emisión de credenciales. Una vez emitidas las credenciales se almacenan en Mouro y son accedidas los los usuarios desde ai·di.
Uso aplicación por aplicativo

2021-07-12 20:47 UTC, tamarabag approved these changes
(Y)

2021-07-12 20:51 UTC, merged