[WIP] Avance documentación de integración entre apps
ong-bitcoin-argentina/DIDI-SSI-Docs pull request #47
Opened 2021-07-14 12:17 UTC by Diegoro21

Armo el pr para que vayan viendo como queda y para que comenten si les parece algún cambio

2021-07-14 17:49 UTC, fedelmar approved these changes

2021-07-15 15:59 UTC, MatiasOS requested changes

2021-07-15 15:59 UTC, MatiasOS commented on docs/developers/deployment/post-deployment.md
> +node key-generator.js
Poné **node key-generator.js** como un bloque de código

2021-07-19 12:48 UTC, MatiasOS submitted a review, later dismissed

2021-07-19 13:15 UTC, tamarabag requested changes
paso algunas cositas  más bien de formato y debería agregarse la referencia al doc firebase-config.md en el doc de post-deployment.md en la instancia que corresponda.

2021-07-19 13:15 UTC, tamarabag commented on docs/developers/deployment/firebase-config.md
> +`loginSuccess`: DeepLink en aidi el cual si se auténtico bien envía el token hacia ronda, en caso negativo lo retorna vacío.
reemplazar "auténtico" por "autenticó"

2021-07-19 13:15 UTC, tamarabag commented on docs/developers/deployment/firebase-config.md
> +`login`: DeepLink en ronda, donde hace referencia al login de aidi, en caso de no estar instalada, redirige a la descarga desde Google Play Store.
DeepLink en ronda, donde hace referencia al login de ai·di que, en caso de no estar instalada en el dispositivo, redirige a la descarga de ai·di desde Google Play Store.

2021-07-19 13:15 UTC, tamarabag commented on docs/developers/deployment/post-deployment.md
> +	};
cambiar formato de texto a código

2021-07-19 13:15 UTC, tamarabag commented on docs/developers/deployment/post-deployment.md
> +	}
idem formato de texto a código

2021-07-19 13:15 UTC, tamarabag commented on docs/developers/deployment/post-deployment.md
> +	};
formato de texto a código

2021-07-19 13:15 UTC, tamarabag commented on docs/developers/deployment/post-deployment.md
> +	}
formato

2021-07-19 13:15 UTC, tamarabag commented on docs/developers/deployment/post-deployment.md
> +https://github.com/uport-project/react-native-uport-signer
[Repositorio uPort - React Native uPort Signer](https://github.com/uport-project/react-native-uport-signer)

2021-07-19 13:15 UTC, tamarabag commented on docs/developers/deployment/post-deployment.md
> +https://github.com/decentralized-identity/did-jwt
[Repositorio Decentralized Identity - DID JWT](https://github.com/decentralized-identity/did-jwt)

2021-07-19 13:15 UTC, tamarabag commented on docs/developers/deployment/post-deployment.md
> +https://www.npmjs.com/package/uport-credentials
[uPort Credentials](https://www.npmjs.com/package/uport-credentials)

2021-07-19 18:20 UTC, tamarabag approved these changes

2021-07-19 19:22 UTC, merged