[WIP] Changelog de versiones 0.6.0 y 0.6.1
ong-bitcoin-argentina/DIDI-SSI-Docs pull request #51
Opened 2021-08-17 22:46 UTC by fedelmar

2021-08-18 20:42 UTC, MatiasOS requested changes
Revisar ortografía

2021-08-19 11:16 UTC, tamarabag requested changes

2021-08-19 11:16 UTC, tamarabag commented on docs/changelog/v0.6.x.md
> +- [Semillas] Se corrigio bug en la creación de credenciales de vivienda.
Se corrigió

2021-08-19 11:16 UTC, tamarabag commented on docs/changelog/v0.6.x.md
> +- [Semillas] Se modifico cron para que la sincronización se ejecute todos los dias a las 8am.
Se modificó el cron para que la sincronización se ejecute una sola vez al día a las 8am.

2021-08-19 11:16 UTC, tamarabag commented on docs/changelog/v0.6.x.md
> +- [Semillas] Se corrigio flujo de validación de carga de credenciales de vivienda mediante excel.
Se corrigió el flujo (...) --> qué modificación hubo en el flujo?

2021-08-19 11:16 UTC, tamarabag commented on docs/changelog/v0.6.x.md
> +- [Semillas] Se corrigio endpoint de revocar credencial.
Se corrigió el endpoint (...)

2021-08-19 17:28 UTC, MatiasOS approved these changes

2021-09-02 21:16 UTC, merged