Actualizar pasos post deploy
ong-bitcoin-argentina/DIDI-SSI-Docs pull request #56
Opened 2021-09-10 17:13 UTC by fedelmar

- Se agregan a los pasos post deploy el paso de cargar las direcciones en las resdes de test de Ethereum.

2021-09-10 17:17 UTC, tomaslosada approved these changes
Approved!

2021-09-10 17:23 UTC, MatiasOS requested changes
Agregar esos como opciones y tambièn està la opción de metamask https://faucet.metamask.io/

2021-09-10 17:23 UTC, MatiasOS commented on docs/developers/deployment/post-deployment.md
> +	- [**Goerli**](https://faucet.goerli.mudit.blog/)
https://goerli-faucet.slock.it/

2021-09-10 17:23 UTC, MatiasOS commented on docs/developers/deployment/post-deployment.md
> +	- [**Kovan**](https://faucets.chain.link/)
https://gitter.im/kovan-testnet/faucet#

2021-09-10 17:23 UTC, MatiasOS commented on docs/developers/deployment/post-deployment.md
> +	- [**Ropsten**](https://faucet.dimensions.network/)
https://faucet.ropsten.be/

2021-09-13 15:12 UTC, tomaslosada reviewed
Approve!

2021-09-20 15:24 UTC, MatiasOS approved these changes

2021-09-20 15:24 UTC, merged